### ISSUE TITLE
Pip 10 doesn't support pip.req

### ISSUE THREAD

**Issue by gargravarr** [zalando-stups/berry#27]
When trying to install package, errors because it can't find `pip.req`:

```
$ pip install -e .
Obtaining file:///Users/rreis/go/src/github.com/zalando-stups/berry
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/rreis/go/src/github.com/zalando-stups/berry/setup.py", line 11, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/rreis/go/src/github.com/zalando-stups/berry/
```

**Comment by taojang** [comment]
I am having this exact same issue.

**Comment by taojang** [comment]
Is it possible to release the fixed version?
