### ISSUE TITLE
Migrate to new Boto3 AWS Python SDK

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/berry#6]
https://boto3.readthedocs.org/en/latest/guide/migration.html

**Comment by hjacobs** [comment]
This seems to be urgent, users get sporadically:

```
$ senza console myapp.yml
Showing last 25 lines of myapp-1/i-f45b0b79..
berry:   File "/usr/local/lib/python3.4/dist-packages/boto/utils.py", line 224, in retry_url
berry:     boto.log.exception('Caught exception reading instance data')
berry: Message: 'Caught exception reading instance data'
berry: Arguments: ()
berry: ERROR: Unable to read instance data, giving up
berry: Traceback (most recent call last):
berry:   File "/usr/local/bin/berry", line 11, in <module>
berry:     sys.exit(main())
berry:   File "/usr/local/lib/python3.4/dist-packages/berry/cli.py", line 132, in main
berry:     run_berry(args)
berry:   File "/usr/local/lib/python3.4/dist-packages/berry/cli.py", line 62, in run_berry
berry:     s3 = boto.connect_s3()
berry:   File "/usr/local/lib/python3.4/dist-packages/boto/__init__.py", line 141, in connect_s3
berry:     return S3Connection(aws_access_key_id, aws_secret_access_key, **kwargs)
berry:   File "/usr/local/lib/python3.4/dist-packages/boto/s3/connection.py", line 190, in __init__
berry:     validate_certs=validate_certs, profile_name=profile_name)
berry:   File "/usr/local/lib/python3.4/dist-packages/boto/connection.py", line 569, in __init__
berry:     host, config, self.provider, self._required_auth_capability())
berry:   File "/usr/local/lib/python3.4/dist-packages/boto/auth.py", line 987, in get_auth_handler
berry:     'Check your credentials' % (len(names), str(names)))
berry: boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials
```

**Comment by snackycracky** [comment]
:+1:

**Comment by snackycracky** [comment]
https://github.com/boto/boto/pull/3370

**Comment by hjacobs** [comment]
Released in https://github.com/zalando-stups/berry/releases/tag/1.0.11
